import os 
import sys
logo = "SETUP TOOL BY AHMED!"
print("welcome!")
os.system("clear")
print(logo)
print("apt update!")
os.system("apt update")
print("Done!")
os.system("clear")
print(logo)
print("apt upgrade")
os.system("apt upgrade")
print("Done")
os.system("clear")
print(logo)
print("install git")
os.system("apt-get install git -y")
print("Done")
os.system("clear")
print(logo)
print("install golang")
os.system("apt-get install golang -y")
print("Done")
os.system("clear")
print(logo)
print("install perl")
os.system("apt-get install perl -y")
print("Done")
os.system("clear")
print(logo)
print("install python3")
os.system("apt-get install python3 -y")
print("Done")
os.system("clear")
print(logo)
print("install python2")
os.system("apt-get install python2 -y")
print("Done")
os.system("clear")
print(logo)
print("install python3-pip")
os.system("apt-get install python3-pip -y")
print("Done")
os.system("clear")
print(logo)
print("install nodejs")
os.system("apt-get install nodejs -y")
print("Done")
os.system("clear")
print(logo)
print("install wget")
os.system("apt-get install wget -y")
print("Done")
os.system("clear")
print(logo)
print("install npm")
os.system("apt-get install npm -y")
print("Done")
os.system("clear")
print(logo)
print("npm i requests")
os.system("npm i requests")
print("Done")
os.system("clear")
print(logo)
print("npm i https-proxy-agent")
os.system("npm i https-proxy-agent")
print("npm i crypto-random-string")
os.system("npm i crypto-random-string")
print("npm i events")
os.system("npm i events")
print("npm i fs")
os.system("npm i fs")
print("npm i net")
os.system("npm i net")
print("npm i cloudscraper")
os.system("npm i cloudscraper")
print("npm i request")
os.system("npm i request")
print("npm i hcaptcha-solver")
os.system("npm i hcaptcha-solver")
print("npm i randomstring")
os.system("npm i randomstring")
print("npm i cluster")
os.system("npm i cluster")
print("npm i cloudflare-bypasser")
os.system("npm i cloudflare-bypasser")
print("pip3 install -r requirements.txt")
os.system("pip3 install -r requirements.txt")
print("wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb")
os.system("wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb")
print("apt-get install ./google-chrome-stable_current_amd64.deb")
os.system("apt-get install ./google-chrome-stable_current_amd64.deb")
print("ulimit -n 999999")
os.system("ulimit -n 999999")
print("chmod 777 *")
os.system("chmod 777 *")
print("python3 c2.py")
os.system("python3 c2.py")